POST https://localhost:7240/breakfast/
Content-Type: application/json

{
    "name": "Vegan",
    "description": "Something",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory":"Salad"
    "Sweet": "Cookie"
}